In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [18]:
df=pd.read_csv('Titanic-Dataset.csv')[['Age', 'Pclass', 'SibSp', 'Parch','Survived']]

In [19]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [20]:
df.dropna(inplace=True)

In [21]:
df.shape

(714, 5)

In [22]:
X=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [23]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [24]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [25]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

# Applying the Family Construction

In [26]:
df.columns

Index(['Age', 'Pclass', 'SibSp', 'Parch', 'Survived'], dtype='object')

In [27]:
X['Family_Size']=X['Parch']+X['SibSp']+1

In [28]:
X.head()

    Age  Pclass  SibSp  Parch  Family_Size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [29]:
def myfunc(num):
    if num==1:
        return 0
    elif num>1 and num<=4:
        return 1
    else:
        return 2

In [32]:
X['Family_type']=X['Family_Size'].apply(myfunc)

In [33]:
X.head()

    Age  Pclass  SibSp  Parch  Family_Size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [34]:
X.drop(columns=['Parch', 'SibSp', 'Family_Size'], inplace=True)

In [35]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [36]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.7003174603174602)

# **Feature Splitting **

In [37]:
df=pd.read_csv('Titanic-Dataset.csv')

In [38]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [40]:
df['Title']=df['Name'].str.split(',',expand=True)[1].str.split('.', expand=True)[0]

In [41]:
df['Title']

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: Title, Length: 891, dtype: object

In [44]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64